#!/bin/sh

get_blight() {
	CARD=`ls /sys/class/backlight | head -n 1`

	if [[ "$CARD" == *"intel_"* ]]; then
		BNESS=`xbacklight -get`
		LIGHT=${BNESS%.*}
	else
		BNESS=`blight -d $CARD get brightness`
		PERC="$(($BNESS*100/255))"
		LIGHT=${PERC%.*}
	fi

	echo "$LIGHT"
}

