#!/bin/bash

get_status ()
{
    if [ $(playerctl status) = "Playing" ]; then
        echo "  "
    elif [ $(playerctl status) = "Paused" ]; then
        echo "  "
    else
        echo "  "
    fi
}

if [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--toggle" ]]; then
	playerctl play-pause
elif [[ "$1" == "--next" ]]; then
	{ playerctl next; get_cover; }
elif [[ "$1" == "--prev" ]]; then
	{ playerctl previous; get_cover; }
fi
